# Generated by Django 4.2.4 on 2023-08-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bearer",
                    models.CharField(blank=True, max_length=24, null=True, unique=True),
                ),
                ("email", models.EmailField(max_length=254)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=512)),
            ],
        ),
    ]
