[tool.pyright]
include = ["ParadoxiBox", "songs"]
defineConstant = { DEBUG = true }
venv = ".venv"
venvPath = "."

reportMissingImports = true
reportMissingTypeStubs = false
strictListInference = true
strictDictionaryInference = true
strictSetInference = true
reportFunctionMemberAccess = "warning"
reportImportCycles = "error"
reportUnusedImport = "information"
reportUnusedClass = "information"
reportUnusedFunction = "information"
reportUnusedVariable = "information"
reportDuplicateImport = "information"
reportUntypedFunctionDecorator = "information"
reportUntypedClassDecorator = "information"
reportUntypedBaseClass = "information"
reportUntypedNamedTuple = "information"
reportPrivateUsage = "warning"
reportPrivateImportUsage = "warning"
reportConstantRedefinition = "information"
reportDeprecated = "warning"
reportIncompatibleMethodOverride = "error"
reportIncompatibleVariableOverride = "information"
reportInconsistentConstructor = "error"
reportOverlappingOverload = "warning"
reportMissingSuperCall = "warning"
reportUninitializedInstanceVariable = "warning"
reportMissingParameterType = "information"
reportMissingTypeArgument = "information"
reportUnnecessaryIsInstance = "information"
reportUnnecessaryComparison = "information"
reportUnnecessaryContains = "warning"
reportImplicitStringConcatenation = "information"
reportUnusedExpression = "information"
reportMatchNotExhaustive = "warning"
reportShadowedImports = "warning"

executionEnvironments = [
  { root = "src" }
]
