# Generated by Django 4.2.4 on 2023-08-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=255)),
                ("source_link", models.URLField(max_length=255)),
                ("path_music", models.FileField(upload_to="songs/")),
                ("duration", models.DurationField()),
                ("thumbnail", models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("songs", models.ManyToManyField(to="songs.song")),
            ],
        ),
    ]
