name: Build and release

on:
  push:
    tags:
      - '*'

jobs:

  release-front-cli:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install -y gcc make git libssl-dev build-essential gcc-mingw-w64-x86-64

      - name: Install vlang
        run: |
          git clone https://github.com/vlang/v.git
          cd v
          make
          sudo ./v symlink

      - name: Build front-cli
        run: |
          cd front-cli
          make paradoxibox-cli-prod-linux
          make paradoxibox-cli-prod-windows

      - name: Upload to artifact (binary linux)
        uses: actions/upload-artifact@v3
        with:
          name: paradoxibox-cli-linux
          path: front-cli/paradoxibox-cli

      - name: Upload to artifact (binary windows)
        uses: actions/upload-artifact@v3
        with:
          name: paradoxibox-cli-windows.exe
          path: front-cli/paradoxibox-cli.exe

      - name: Upload to release (binary linux)
        uses: Shopify/upload-to-release@v1
        with:
          name: paradoxibox-cli-linux
          path: front-cli/paradoxibox-cli
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          content-type: application/octet-streaml

      - name: Upload to release (binary windows)
        uses: Shopify/upload-to-release@v1
        with:
          name: paradoxibox-cli.exe
          path: front-cli/paradoxibox-cli.exe
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          content-type: application/octet-streaml

  release-back:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install -y tar gzip


      - name: Package back folder
        run: tar -zcvf paradoxibox-back.tar.gz back

      - name: Upload to artifact (python source archive)
        uses: actions/upload-artifact@v3
        with:
          name: paradoxibox-back.tar.gz
          path: paradoxibox-back.tar.gz

      - name: Upload to release (python source archive)
        uses: Shopify/upload-to-release@v1
        with:
          name: paradoxibox-back.tar.gz
          path: paradoxibox-back.tar.gz
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          content-type: application/gzip
